version = "1.0"

[metadata]

[verifier]
timeout_sec = 600.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
allow_internet = true

[_seekingdata]
name = "github-task-20260314140411-20260314140411-8f3d3ced"
description = ""
status = "failed"
created_at = "2026-03-14T16:36:30.411256"
updated_at = "2026-03-14T16:36:32.960628"

[verifier.env]
